name: practicing CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run : echo "Setting up Environment"
      - name: Intall Dependencies
        run: echo "Installed Dependencies"
      - name: Give Build 
        run: echo "Npm Build"
      - name: checkout repo
        run: echo "checkout to repo"
      - name: Upload artifact
        run: echo "Upload Artifact the build file"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: echo "checkout to repo"
      - name: Download Artifacts
        run: echo "Downloading artifacts"
      - name: testing phase
        run: echo "npm test"
      - name: sonarqube 
        run: echo "security testing"
      - name: scan the image
        run: echo "scanning the image using Trivy"

  deploy:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps: 
      - name: argocd 
        run: echo "deploy latest image in kubernetes"
      - name: Successfully Done
        run: echo "Deployment Done"
      
