name: CICD - Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: echo "npm install"

      - name: Build the application
        run: echo "npm run build"

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Test 
        run: echo "Testing successfully completed"
  
  deployment:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: "Deployment"
        run: echo "deployment successfully completed"
