name: CICD - Pipeline for upload and download

on:
  push:
    branches:
      - main

jobs:

  uploadfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v7
        with: 
          name: all files
          path: .
      - name: Upload file
        run : echo "Uploading Files....."
        
  download:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/download-artifact@v8
        with:
          name: all files
      - name: List the downloaded file
        run: ls -l